// src/components/Navbar.tsx
"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { Menu, X, ArrowUpRight } from "lucide-react";

const links = [
  { label: "Services", href: "#services", id: "services" },
  { label: "Why Us",   href: "#why-us",   id: "why-us" },
  { label: "Work",     href: "#work",     id: "work" },
  { label: "Contact",  href: "#contact",  id: "contact" },
];

const EASE_OUT = [0.23, 1, 0.32, 1] as const;

export default function Navbar() {
  const [scrolled, setScrolled] = useState(false);
  const [open, setOpen]         = useState(false);
  const [active, setActive]     = useState<string>("");

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 16);
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  // Scroll-spy: highlight the nav link for the section in view.
  useEffect(() => {
    const sections = links
      .map((l) => document.getElementById(l.id))
      .filter((el): el is HTMLElement => el !== null);

    const observer = new IntersectionObserver(
      (entries) => {
        const visible = entries
          .filter((e) => e.isIntersecting)
          .sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0];
        if (visible) setActive(visible.target.id);
      },
      { rootMargin: "-45% 0px -45% 0px", threshold: [0, 0.25, 0.5] },
    );

    sections.forEach((s) => observer.observe(s));
    return () => observer.disconnect();
  }, []);

  return (
    <>
      <header
        className="fixed top-0 left-0 right-0 z-50 transition-all duration-300"
        style={{
          backgroundColor: scrolled ? "rgba(8,9,11,0.72)" : "transparent",
          backdropFilter:  scrolled ? "blur(18px) saturate(140%)" : "none",
          boxShadow: scrolled
            ? "inset 0 1px 0 rgba(255,255,255,0.05), 0 1px 0 var(--color-border), 0 20px 40px -32px rgba(0,0,0,0.8)"
            : "none",
          padding: scrolled ? "12px 0" : "22px 0",
          transitionTimingFunction: "var(--ease-out)",
        }}
      >
        <div className="container-custom flex items-center justify-between">

          {/* Wordmark */}
          <Link href="/" className="flex items-baseline gap-1.5 btn-press" aria-label="WUSLA home">
            <span className="font-display text-lg font-bold tracking-tight" style={{ color: "var(--color-text)" }}>
              wusla
            </span>
            <span
              className="w-1.5 h-1.5 rounded-full animate-pulse-dot"
              style={{ backgroundColor: "var(--color-emerald)", boxShadow: "0 0 8px var(--color-emerald)" }}
            />
          </Link>

          {/* Desktop links */}
          <nav className="hidden md:flex items-center gap-9">
            {links.map((l) => (
              <Link
                key={l.label}
                href={l.href}
                data-active={active === l.id}
                className="link-underline text-sm font-medium transition-colors duration-200"
                style={{ color: active === l.id ? "var(--color-text)" : "var(--color-text-muted)" }}
              >
                {l.label}
              </Link>
            ))}
          </nav>

          {/* CTA + mobile toggle */}
          <div className="flex items-center gap-3">
            <Link
              href="#contact"
              className="hidden md:inline-flex items-center gap-1.5 text-sm font-semibold px-4 py-2 rounded-[10px] btn-press"
              style={{
                color: "var(--color-text)",
                border: "1px solid var(--color-border-bright)",
                transition: "border-color 200ms var(--ease-out), background-color 200ms var(--ease-out), transform 160ms var(--ease-out)",
              }}
              onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = "var(--color-bg-card)"; }}
              onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = "transparent"; }}
            >
              Start a project
              <ArrowUpRight className="w-4 h-4" style={{ color: "var(--color-emerald)" }} />
            </Link>

            <button
              className="md:hidden p-2 rounded-lg btn-press"
              style={{ color: "var(--color-text)" }}
              onClick={() => setOpen(true)}
              aria-label="Open menu"
              aria-expanded={open}
            >
              <Menu className="w-5 h-5" />
            </button>
          </div>
        </div>
      </header>

      {/* Mobile overlay */}
      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2, ease: EASE_OUT }}
            className="fixed inset-0 z-50 flex flex-col md:hidden"
            style={{ backgroundColor: "var(--color-bg)" }}
          >
            <div
              className="container-custom flex items-center justify-between py-5"
              style={{ borderBottom: "1px solid var(--color-border)" }}
            >
              <span className="font-display text-lg font-bold" style={{ color: "var(--color-text)" }}>
                wusla<span style={{ color: "var(--color-emerald)" }}>.</span>
              </span>
              <button
                onClick={() => setOpen(false)}
                className="p-2 rounded-lg btn-press"
                style={{ color: "var(--color-text-muted)" }}
                aria-label="Close menu"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <nav className="flex-1 container-custom flex flex-col justify-center gap-1">
              {links.map((l, i) => (
                <motion.div
                  key={l.label}
                  initial={{ opacity: 0, y: 16 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.05, ease: EASE_OUT, duration: 0.3 }}
                >
                  <Link
                    href={l.href}
                    onClick={() => setOpen(false)}
                    className="flex items-center justify-between py-5 font-display text-3xl font-bold"
                    style={{ color: "var(--color-text)", borderBottom: "1px solid var(--color-border)" }}
                  >
                    <span>{l.label}</span>
                    <ArrowUpRight className="w-6 h-6" style={{ color: "var(--color-emerald)" }} />
                  </Link>
                </motion.div>
              ))}
            </nav>

            <div className="container-custom py-6">
              <Link
                href="#contact"
                onClick={() => setOpen(false)}
                className="block w-full text-center font-semibold py-4 rounded-[10px] btn-press"
                style={{ backgroundColor: "var(--color-emerald)", color: "#04140D" }}
              >
                Start a project
              </Link>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}

// app/components/Navbar.vue
<script setup lang="ts">
import { Menu, X, ArrowUpRight } from "lucide-vue-next";

const open = ref(false);
const route = useRoute();
const hasScrolled = ref(false);
const isHome = computed(() => route.path === "/");
const links = [
  { label: "Company", href: "/company" },
  { label: "Applications", href: "/applications" },
  { label: "Work", href: "/portfolio" },
];

function updateHeader() {
  hasScrolled.value = window.scrollY > 36;
}

onMounted(() => {
  updateHeader();
  window.addEventListener("scroll", updateHeader, { passive: true });
});

onBeforeUnmount(() => window.removeEventListener("scroll", updateHeader));

watch(() => route.path, () => {
  open.value = false;
  if (import.meta.client) updateHeader();
});
</script>

<template>
  <header class="site-header" :class="{ 'is-home': isHome, 'has-scrolled': hasScrolled }">
    <div class="container-custom header-inner">
      <NuxtLink to="/" class="wordmark" aria-label="WUSLA home"><span aria-hidden="true">WUSLA</span></NuxtLink>
      <nav class="desktop-nav" aria-label="Primary navigation"><NuxtLink v-for="link in links" :key="link.label" :to="link.href">{{ link.label }}</NuxtLink></nav>
      <NuxtLink to="/#contact" class="header-cta">Start a conversation <ArrowUpRight :size="15" /></NuxtLink>
      <button class="mobile-toggle" :aria-expanded="open" :aria-label="open ? 'Close navigation' : 'Open navigation'" @click="open = !open"><X v-if="open" :size="21" /><Menu v-else :size="21" /></button>
    </div>
    <nav v-if="open" class="mobile-nav" aria-label="Mobile navigation"><NuxtLink v-for="link in links" :key="link.label" :to="link.href" @click="open = false">{{ link.label }} <ArrowUpRight :size="18" /></NuxtLink><NuxtLink to="/#contact" @click="open = false">Contact <ArrowUpRight :size="18" /></NuxtLink></nav>
  </header>
</template>

<style scoped>
.site-header{position:fixed;z-index:50;top:0;left:0;right:0;color:#f5f1e4;background:#195440;border-bottom:1px solid rgba(245,250,247,.16);transition:background-color .38s var(--ease-out),border-color .38s var(--ease-out),backdrop-filter .38s var(--ease-out)}.site-header.is-home:not(.has-scrolled){background:transparent;border-color:transparent}.site-header.has-scrolled{background:rgba(6,74,55,.96);border-color:rgba(245,250,247,.18);backdrop-filter:blur(14px)}.header-inner{height:74px;display:grid;grid-template-columns:1fr auto 1fr;align-items:center}.wordmark{display:inline-flex;align-items:center;justify-self:start;color:#f5f1e4;font:760 1.78rem/.9 var(--font-display);letter-spacing:.075em;transition:color 180ms var(--ease-out),transform 180ms var(--ease-out)}.wordmark:hover{color:#c9f0dd}.wordmark:active{transform:scale(.98)}.desktop-nav{display:flex;gap:2.2rem}.desktop-nav a{position:relative;font:600 .7rem/1 var(--font-mono);text-transform:uppercase;letter-spacing:.1em;color:#d7ede4;transition:color .2s}.desktop-nav a::after{position:absolute;right:0;bottom:-.55rem;left:0;height:1px;content:"";background:#c9f0dd;transform:scaleX(0);transform-origin:left;transition:transform .25s var(--ease-out)}.desktop-nav a.router-link-active::after,.desktop-nav a:hover::after{transform:scaleX(1)}.desktop-nav a.router-link-active,.desktop-nav a:hover{color:#fff}.header-cta{justify-self:end;display:inline-flex;align-items:center;gap:.45rem;background:#c9f0dd;color:#004a36;padding:.73rem .9rem;font-weight:700;font-size:.82rem;transition:transform .25s var(--ease-out),background-color .25s var(--ease-out)}.header-cta:hover{background:#edf6ef;transform:translateY(-2px)}.mobile-toggle,.mobile-nav{display:none}@media(max-width:767px){.header-inner{height:66px;grid-template-columns:1fr auto}.wordmark{font-size:1.55rem}.desktop-nav,.header-cta{display:none}.mobile-toggle{display:flex;align-items:center;justify-content:center;min-width:44px;min-height:44px;color:#f5f1e4;padding:.5rem}.mobile-nav{position:absolute;top:66px;right:0;left:0;display:flex;max-height:calc(100svh - 66px);flex-direction:column;overflow-y:auto;padding:1rem 1.5rem 1.5rem;background:#195440;border-top:1px solid rgba(245,250,247,.2);box-shadow:0 8px 12px rgba(0,45,33,.18)}.mobile-nav a{display:flex;align-items:center;justify-content:space-between;min-height:56px;padding:1.1rem 0;border-bottom:1px solid rgba(245,250,247,.15);font-size:1.1rem;font-weight:650;color:#f5f1e4}}
</style>
